// Generated by Dagger (https://google.github.io/dagger).
package com.rain.weather.ui.fragment;

import androidx.lifecycle.ViewModelProvider;
import dagger.MembersInjector;
import javax.inject.Provider;

public final class WeatherFragment_MembersInjector implements MembersInjector<WeatherFragment> {
  private final Provider<ViewModelProvider.Factory> viewModelFactoryProvider;

  public WeatherFragment_MembersInjector(
      Provider<ViewModelProvider.Factory> viewModelFactoryProvider) {
    this.viewModelFactoryProvider = viewModelFactoryProvider;
  }

  public static MembersInjector<WeatherFragment> create(
      Provider<ViewModelProvider.Factory> viewModelFactoryProvider) {
    return new WeatherFragment_MembersInjector(viewModelFactoryProvider);
  }

  @Override
  public void injectMembers(WeatherFragment instance) {
    injectViewModelFactory(instance, viewModelFactoryProvider.get());
  }

  public static void injectViewModelFactory(
      WeatherFragment instance, ViewModelProvider.Factory viewModelFactory) {
    instance.viewModelFactory = viewModelFactory;
  }
}
